# Generated by Django 5.1.6 on 2025-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_cosmica_api', '0006_alter_comment_article_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profiles/images/%Y/%m/%d/'),
        ),
    ]
